FROM golang:1.20.4-alpine3.17
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN CGO_ENABLED=0 go build -o /bin/app ./cmd

FROM alpine
WORKDIR /src

COPY --from=0 /bin/app /bin/app
COPY --from=0 /src/config/.env /src/config/.env
COPY --from=0 /src/config/end_points.json /src/config/end_points.json

ENTRYPOINT ["/bin/app"]